mybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Effort Controllers ---------------------------------------
  left_front_Wheel_effort_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_front_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}

  left_back_Wheel_effort_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_back_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
    
  right_front_Wheel_effort_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_front_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_back_Wheel_effort_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_back_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
